### ISSUE TITLE
24hr usage

### ISSUE THREAD

**Issue by hphd70** [Art-of-WiFi/UniFi-API-browser#101]
is there a way to get the 24hr usage of a client as it is visible under "client devices" of the unifi controller webinterface?
thanks a lot for this great tool!

**Comment by malle-pietje** [comment]
Yes, use this method:
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/src/Client.php#L722

**Comment by malle-pietje** [comment]
Or use one of the stat_*_user() methods depending on your requirements.
