### ISSUE TITLE
All devices

### ISSUE THREAD

**Issue by kjetilpp** [Art-of-WiFi/UniFi-API-browser#104]
Hello! Is there a way to list all devices on all sites?

**Comment by malle-pietje** [comment]
Not with how the API Browser tool is structured where you can fetch collections within the context of a site after selecting a controller.

With our (paid) UniFi Device Search Tool we fetch the relevant details of all the devices across all sites within a controller. This is done by "cycling" through all sites and merging all the devices into a single "collection".

More details can be found here:
https://artofwifi.net/portfolio/unifi-device-search-tool/
