### ISSUE TITLE
Removing users across all sites

### ISSUE THREAD

**Issue by tobylauncesonit** [Art-of-WiFi/UniFi-API-browser#105]
Hi, I'm looking to remove a user across all sites and since there doesn't seem to be a native way of doing this as I need to be able to remove an employee when they leave and since we have over 70 sites it is a very time-consuming process to delete the user manually.

I spoke to Erik through email and he suggested to use delete_device($mac) method.

How would I go about doing this?

Thanks!

**Comment by malle-pietje** [comment]
Please post this issue here:
https://github.com/Art-of-WiFi/UniFi-API-client/issues

I'm afraid you have selected the wrong repo for this question. 😉
