### ISSUE TITLE
Permission denied (13) when loading sites

### ISSUE THREAD

**Issue by oiner23** [Art-of-WiFi/UniFi-API-browser#107]
Hi there, 
I feel like I'm missing something simple.
We get the error "We encountered the following error: we are unable to connect to the UniFi controller, Permission denied (13)!" when trying to load the sites.
Enabled the debug logs in config.php but the php and httpd error logs only contain similar information "we have a connection error Permission denied (13)" 

We can successfully wget and telnet to the controller from the browser server. 
Triple checked the username and password in config.php. Created a new admin user in the controller and used those details in the config.php with the same result. Tested with and without a users.php configured. PHP version and cURL versions are above what is in the requirements. 

Controller is running version 6.5.x however that doesnt appear in the about on the browser page.

![image](https://github.com/Art-of-WiFi/UniFi-API-browser/assets/136664290/3ad8b06d-b163-4446-b3f7-bd975a27b5b8)

Would apprecate any help pointing me in the right direction.
Cheers.

**Comment by malle-pietje** [comment]
Hmm, odd. Sounds like a connectivity issue where something is blocking access from this server to port 8443 on the controller. The easiest way to confirm this is by using a command-line browser (e.g. links2) to connect from the server to the controller.

**Comment by oiner23** [comment]
Good question. In testing it today we can get it to successfully load in links2, and load and login firefox with forwarding the display via X11.

**Comment by malle-pietje** [comment]
Which exact Operating System version are you running?

**Comment by malle-pietje** [comment]
And is this a software-based controller or a UniFi OS console? Just to be sure…

**Comment by oiner23** [comment]
Yes thats right, a software-based controller and API Browser is running on AlmaLinux 9.2

**Comment by malle-pietje** [comment]
Is there perhaps SELinux running on the server?

**Comment by malle-pietje** [comment]
Seems to be enabled by default:
https://linuxconfig.org/how-to-disable-selinux-on-almalinux

Disable SELinux completely and test again.

**Comment by oiner23** [comment]
I should have double checked we turned that off. It has resolved our permission denied error.

Unfortunately now we get "Error loading sites or no sites available" on the website. And in the php logs "PHP Notice:  JSON decode error: Syntax error, malformed JSON in /var/www/html/UniFi-API-browser/vendor/art-of-wifi/unifi-api-client/src/Client.php on line 3769". We'll do some troubleshooting on this, maybe start from scratch.

Thank you for your help.

**Comment by malle-pietje** [comment]
Thanks for the feedback. To troubleshoot your current error it will help to enable debug mode.
