### ISSUE TITLE
Docker image update

### ISSUE THREAD

**Issue by SamKr** [Art-of-WiFi/UniFi-API-browser#114]
Hi team,

I noticed that the [docker image](https://hub.docker.com/r/scyto/unifibrowser) is still on version 2.0.23 and has been for two years, while 2.0.26 is out. Are there plans to get it up to date? The API client is getting a lot of love as well, perhaps both the browser and its docker image can be updated with the latest API client? 

There's no real bug I'm encountering atm, just wondering :)

**Comment by malle-pietje** [comment]
Hi @SamKr , I’m not involved in maintaining the Docker image at all so I recommend reaching out to @scyto, maybe they can provide an update?

**Comment by malle-pietje** [comment]
I’ll try to push a new update here which includes the latest version of the PHP API client case in the next couple of days. 🤞

**Comment by SamKr** [comment]
Thanks for the info, [posted a ticket](https://github.com/scyto/docker-UnifiBrowser/issues/16) 🤞

**Comment by malle-pietje** [comment]
Update pushed.

**Comment by SamKr** [comment]
Perfect! Thanks :)

**Comment by scyto** [comment]
docker now updated
https://github.com/scyto/docker-UnifiBrowser/issues/16#issuecomment-2408112123
