### ISSUE TITLE
change poe status on a port from a switch

### ISSUE THREAD

**Issue by valshare** [Art-of-WiFi/UniFi-API-browser#31]
Hello,

thanks for your great API Browser. I am searching for a way to change the port status from a switch. specific the poe status. Is there a way to do it over the API Browser?

Regards, Valle

**Comment by malle-pietje** [comment]
Thanks, glad you like it! This currently not yet supported by the API client class since it is not as straightforward to implement as the other functions. It is however feasible, just requires some thought and time...
