### ISSUE TITLE
help needed

### ISSUE THREAD

**Issue by mikemasam** [Art-of-WiFi/UniFi-API-browser#38]
How can i authenticate user using the voucher i have just created..?

**Comment by malle-pietje** [comment]
There is no way to use a voucher to authorise a guest device in a straightforward manner. The best way to currently do this is by reading the voucher attributes (after the code has been submitted by the user), authorise the device according to those attributes like you would normally do, then revoke the voucher to prevent it from being used again.

**Comment by mikemasam** [comment]
Ooooh, now this is getting even harder, is there a method/url i can call to get voucher attrobutes as on the source code there isn't one..?

**Comment by malle-pietje** [comment]
There is: list vouchers using the stat_voucher() method/function and search it for the code.

**Comment by mikemasam** [comment]
Oooh, thanks, your a savior ,
one more thing, is there a way to produce this {   9MB's of 100MB's used  } using stat_client(mac)

**Comment by malle-pietje** [comment]
You're welcome!

For that insight you will need to merge the user object with it's associated authorization object.

**Comment by malle-pietje** [comment]
here's an example of what the results could look like:
![auths](https://user-images.githubusercontent.com/12016131/29213111-1b1b00f6-7ea2-11e7-80a1-0ae21c868cb3.PNG)

**Comment by mikemasam** [comment]
so what if there is millions of vouchers created every minute and someone comes with a voucher which is 1 year old, that will be a very long list to go through untill i find the voucher, how do you handle that...?

**Comment by malle-pietje** [comment]
Show me a site where that is the case (why would you create multi-M vouchers per minute??)... But if you do have such a site, you'll probably need to figure out a different way. But in that case there should be some budget available as well.
