### ISSUE TITLE
Alternative UniFi HotSpot Manager

### ISSUE THREAD

**Issue by ghost** [Art-of-WiFi/UniFi-API-browser#41]
Hello,

I just wanted to let you know, that I uploaded a first version of an alternative [UniFi HotSpot Manager](https://github.com/mcmilk/UniFi-HotSpot-Manager)

It's based on your great [UniFi PHP API](https://github.com/Art-of-WiFi/UniFi-API-browser/tree/master/phpapi) and works for some weeks in one testing environment now.

When you have some suggestion, just let me know.

PS: You can close this issue or leave it open. It's up to you ;)

Here is an example screenshots of it:
![p1](https://github.com/mcmilk/UniFi-HotSpot-Manager/raw/master/contrib/03_ListGuests.png)

**Comment by malle-pietje** [comment]
This is great stuff! Thanks for sharing.
