### ISSUE TITLE
Restart AP

### ISSUE THREAD

**Issue by TCURT15** [Art-of-WiFi/UniFi-API-browser#42]
I am having issues with the restart_ap() function. It does not return any output or errors to the error log when I run that function and the AP does not reboot. Is there a specific way it has to be passed (no colons, etc.)? Controller version 5.4.11. Thanks

**Comment by malle-pietje** [comment]
Was this resolved? If yes, maybe you can share the solution so that others can learn?

**Comment by TCURT15** [comment]
I forgot to call the login function before the restart_ap.

**Comment by malle-pietje** [comment]
Thanks!
