### ISSUE TITLE
Make an option to search for mac Address

### ISSUE THREAD

**Issue by kayvanaarssen** [Art-of-WiFi/UniFi-API-browser#43]
Hi,

Could you make an option to search for a Mac Address and show the site that its in.
Now we need to go to every site.
Would be very nice to have an option to search all sites at once and display the mac Address and the Site that the "AP / Mac" is in.

**Comment by malle-pietje** [comment]
Thanks for the suggestion, however, IMHO this does not fit within the purpose of the API browser tool. What you are looking can simply be achieved with custom code that utilises the API client class.

On a side note: I am considering the development of a (paid) reporting tool combined with some other useful utilities for UniFi networks, and this feature would in nicely.

**Comment by kayvanaarssen** [comment]
Do you have more info on that reporting tool?
And would you consider making a simple file to fetch all aps mac addresses for me with the site name next to it?

**Comment by malle-pietje** [comment]
No firm details yet on it, other than it will allow you report on various collections, both stats and managed objects (clients, devices such as APs, switches etc..). Initial output format will be table-based utilising the jQuery DatatTables library, with the ability to export to Excel for further processing/manipulation.

For stats and similar collections, you can have the ability to select date ranges as well to report on. Whether or not I plan to add charts as well depends on the licensing restrictions of my favourite library, HighCharts.

Regarding your report request; I can do that on a paid basis. If you want to discuss further details I suggest we continue the discussion offline, can be in Dutch:wink: Please mail me at erik ATT artofwifi DOTT net.

**Comment by kayvanaarssen** [comment]
Thanks, just send you an Email
