### ISSUE TITLE
Turning WiFi on and off

### ISSUE THREAD

**Issue by gahujipo** [Art-of-WiFi/UniFi-API-browser#46]
A year ago I've implemented on my side a feature in this project to turn wifi off. I'd like to contribute this feature to the project. 

Turning WiFi on and off can be done by changing the wlan_group of an access point, see [here](https://community.ubnt.com/t5/UniFi-Wireless/API-documentation-to-turn-off-WLAN-radios/td-p/916142)
I've created the following function: 
```PHP
    /**
     * Assign device device to another WLAN group (e.g to turn wifi off)
     * -----------------------------------
     * return TRUE on success
	 * required parameter <wlantype_id>  = WLAN type, can be either 'ng' (for WLANs 2G (11n/b/g)) or 'na' (WLANs 5G (11n/a/ac))
     * required parameter <device_id>  = id of the device to be modified
     * required parameter <group_id> = id of the WLAN group to assign device to
     */
    public function set_devicewlangroup($wlantype_id, $device_id, $group_id) {
        if (!$this->is_loggedin) return FALSE;
        $return          = FALSE;
        $json            = json_encode(array('wlan_overrides' => array(),'wlangroup_id_'.$wlantype_id => $group_id ));
	    $content_decoded = json_decode($this->exec_curl($this->baseurl.'/api/s/'.$this->site.'/upd/device/'.$device_id,'json='.$json));
        if (isset($content_decoded->meta->rc)) {
            if ($content_decoded->meta->rc == 'ok') {
                $return = TRUE;
            }
        }
        return $return;
    }
```
You have to call that function like this: 
```PHP
$data      = $unifidata->set_devicewlangroup('ng', '<deviceId>','<wlanGroupID>');
$data      = $unifidata->set_devicewlangroup('na', '<deviceId>','<wlanGroupID>');
```

1. This means that you have to get the deviceID and wlanGroupID first and have to pass those strings to the function. Should I send you a pull request with the code above or should I implement it that way, that there can be passed a leartext Group (e.g. Off) and a cleartext AP name (e.g. "AP Kitchen")? What do you prefer? 
2. How do you prefer to pass additional variables to be passed to the index.php? Should there be an additional 
```PHP
$deviceId = $_GET['deviceId']
$wlanGroupID = $_GET['wlanGroupID']
```
within the switch/case block?

**Comment by malle-pietje** [comment]
@gahujipo thanks for the suggestion!

First question is whether you cannot use the existing function/method to disable an AP? It disables the WLAN completely until you enable the AP again.

Secondly, I'll see how to best add this to the class. I'm leveraging the REST endpoints for all new functions methods by implementing a basic method that allows you to push a JSON object containing any configuration item to the REST route. Then for common features, I'll add few "wrapper" functions/methods that leverage the base function. That avoids repetitive code.

Thirdly, implementing this in a ready fashion is not exactly what the API browser is meant for. I'd rather add a basic example to the API client class repo based on your input. Anyone can then use that as a starting point for their specific needs.

**Comment by malle-pietje** [comment]
@gahujipo I've decided to add your function as-is to the class with the next update. I'll also see whether I can add an example. I've named the method/function `set_ap_wlangroup()`

**Comment by gahujipo** [comment]
> First question is whether you cannot use the existing function/method to disable an AP? It disables the WLAN completely until you enable the AP again.

Oh, I missed that method. I will test that, because it seems to be more flexible than my code. 

For second and third point: I unterstood now that the API browser is only for unterstanding the API. I always thought that it is intended to launch the methods of the class as a GUI and was always wondering why there where missing some methods in the web part. 

> @gahujipo I've decided to add your function as-is to the class with the next update. I'll also see whether I can add an example. I've named the method/function set_ap_wlangroup()

Should I send a pull request for that?

**Comment by malle-pietje** [comment]
No problem.

No need for a PR. Maybe you can test this before I commit it?
```php


    /**
     * Assign access point to another WLAN group
     * -----------------------------------------
     * return true on success
     * required parameter <wlantype_id>  = string; WLAN type, can be either 'ng' (for WLANs 2G (11n/b/g)) or 'na' (WLANs 5G (11n/a/ac))
     * required parameter <device_id>    = string; id of the access point to be modified
     * required parameter <wlangroup_id> = string; id of the WLAN group to assign device to
     *
     * NOTES:
     * - can for example be used to turn WiFi off
     */
    public function set_ap_wlangroup($wlantype_id, $device_id, $wlangroup_id) {
        if (!$this->is_loggedin) return false;
        $return          = false;
        $json            = json_encode(['wlan_overrides' => [],'wlangroup_id_'.$wlantype_id => $wlangroup_id]);
        $content_decoded = json_decode($this->exec_curl($this->baseurl.'/api/s/'.$this->site.'/upd/device/'.trim($device_id),'json='.$json));
        return $this->process_response_boolean($content_decoded);
    }
```

**Comment by malle-pietje** [comment]
This assumes you have a recent version of the class with the `process_response_boolean()` private function.

**Comment by gahujipo** [comment]
shure, of course I can test it. Just give me a few days for that.

**Comment by malle-pietje** [comment]
thanks!

**Comment by gahujipo** [comment]
I failed to get the new version up and running, so I couldn't test the code. But I have seen that you already committed the function so I assume that you already did the tests?

**Comment by malle-pietje** [comment]
I haven’t specifically tested this, hoped you could do so;-)

Any specific reason you couldn’t install the new version of the class?
