### ISSUE TITLE
Known clients

### ISSUE THREAD

**Issue by tiransa** [Art-of-WiFi/UniFi-API-browser#47]
hi i need to filter blocked user from unifi api browser. in controller i can brows them by 
 htpps://localhost:8443/manage/site/default/insights/knownclients/1/50/0/configured. i want to get this result from api. please help

**Comment by malle-pietje** [comment]
You can do this programmatically through the API client by using the `stat_allusers()` method/function and selecting the objects which have this property:
```
"blocked": true
```
