### ISSUE TITLE
Error connecting

### ISSUE THREAD

**Issue by spyker78** [Art-of-WiFi/UniFi-API-browser#50]
Good day, I am struggling to get the unifi-api-browser going. I have follow your instructions to but getting now where.
Unifi Controller runs as follow:
OS: Ubuntu server 16.04
Unifi controller ver 5.7.30

Errror Message:
No sites available
This is probably caused by incorrect access rights in the UniFi controller for the credentials provided in config.php, or else check your web server error logs. After updating your credentials, please restart your browser or use the Reset PHP session function in the dropdown menu on the right, before attempting to use the API browser tool again."

![image](https://user-images.githubusercontent.com/31136840/37680461-b03bcc2c-2c8c-11e8-94c0-6e7edabcaa7b.png)

Here are the config.php file. I just used an simple username and password to test. Also remove the last part of the ip address.
config.php: 
![image](https://user-images.githubusercontent.com/31136840/37680706-5f6e39dc-2c8d-11e8-8628-c6d8dd5c8477.png)

If you could please assist I would really appreciated.
Thank you
Gerrit

**Comment by malle-pietje** [comment]
Hi Gerrit (Dutch by any chance?),

I’m puzzled by the screenshots: the modal view doesn’t show any values at all for user name and controller URL? Is the config.php file readable for the web server user and did you actually enter a user name and password combination which has access to the controller? Also, the URL must end in :8443 unless you have changed the default port.

**Comment by spyker78** [comment]
Hi Malle-pietjie,
;8) I am South African but the original Gelderblom are Dutch which we have traces back from when the left Holland and when they had arrived in South Africa. (Sorry got carry away.....)

We got the issue sorted some thing simple. 
Thank you!
Gerrit

**Comment by malle-pietje** [comment]
Nice to hear:smiley: Thanks for the feedback!
