### ISSUE TITLE
New logo for UniFi

### ISSUE THREAD

**Issue by reallinfo** [Art-of-WiFi/UniFi-API-browser#51]
I wanted to contribute to UniFi. I designed a logo for UniFi. If you like it, I'll send you the files.

Do not hesitate to say if there is something you want to change. Color bla bla...

Which one do you prefer?

![unifi](https://user-images.githubusercontent.com/36298335/38214680-1150c7c4-36ce-11e8-8416-33852d58a3fc.jpg)

**Comment by malle-pietje** [comment]
Thanks but I’m not looking to add a custom logo since the original name and logo are copywrited.
