### ISSUE TITLE
enable/disable clients

### ISSUE THREAD

**Issue by rhamblen** [Art-of-WiFi/UniFi-API-browser#52]
Hi
I've just come across this, and wondered before I start playing with it, can we configure clients or more specifically enable and disable clients?
Reason... it would be simple to create am HTML scheduler for clients to enable and disable them if you have the basic functionality in the code here!

**Comment by malle-pietje** [comment]
With clients you mean WLAN client devices? In that case the answer is yes.

To develop your own custom code it is recommended to use the stand-alone API client class from here:
https://github.com/Art-of-WiFi/UniFi-API-client

Simply search through the source code for "client device" here:
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/src/Client.php

Also see this example how to authorize a client device:
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/examples/auth_guest_basic.php

This new method might also be of use:
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/src/Client.php#L377-L401
