### ISSUE TITLE
set_ap_wlangroup not functioning

### ISSUE THREAD

**Issue by falenx** [Art-of-WiFi/UniFi-API-browser#53]
Hello, 
I love you work, great job
Recently however the set_ap_wlangroup function has stopped working, it worked for us in the past. A few months ago that particular function just stopped working and now my script will still create the wlan group and the wlan but wont set it to the ap

**Comment by malle-pietje** [comment]
Please create an issue here: https://github.com/Art-of-WiFi/UniFi-API-client/issues
This issue is not related to the API browser tool.

**Comment by malle-pietje** [comment]
Glad you appreciate the efforts!
