### ISSUE TITLE
Disabling guest WLAN not working properly

### ISSUE THREAD

**Issue by msanchezt** [Art-of-WiFi/UniFi-API-browser#54]
I've detected an issue when disabling guest WLAN.

All works fine when I have just 1 single AP.

But when adding a 2nd AP, disabling the guest WLAN only disables 3 of them instead of the 4 of them
(2,4GHz and 5Ghz for the AP 1 and AP 2).

The guest WLAN on 1 of the AP stays enabled after running the disable command. If I run the command a second time, it does nothing (I think it detects no changes so, so does not trigger the commit.

I'm using this 2 AP models:
- UniFi AP-AC-Lite
- UniFi AP-AC-LR

**Comment by malle-pietje** [comment]
I cannot confirm this I’m afraid. The API client performs the same request as the UI so if I were I would check if it works through the UI.

**Comment by msanchezt** [comment]
You are right, same behavior if I do this through the UI.

**Comment by msanchezt** [comment]
Seems the value was overwritten on the UniFi AP-AC-LR. Once undone, all is working properly.

Thanks.

**Comment by malle-pietje** [comment]
Good to hear, thanks for the feedback!
