### ISSUE TITLE
Get list of "Known Clients"

### ISSUE THREAD

**Issue by jenskuespert** [Art-of-WiFi/UniFi-API-browser#56]
The WebUI allows listing of known clients (in the Insights-Section).

I would like to be able, to get a list of these clients. Background: We block unknown clients on a regular basis. The count of blocked devices is limited, so my plan is to remove the oldest entry in this list.

Is there any chance to do this with the available API?

**Comment by malle-pietje** [comment]
Sure, use the stat_allusers() method to fetch the details of all user connected in the past X hours:
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/src/Client.php#L938-L958

Then do what you want with each of the objects in the collection it returns. For example, block or forget devices.

**Comment by jenskuespert** [comment]
Great, that did the trick. Thanks for the fast help.

**Comment by malle-pietje** [comment]
You're welcome!
