### ISSUE TITLE
Heres a container for your app

### ISSUE THREAD

**Issue by benderstwin** [Art-of-WiFi/UniFi-API-browser#57]
I built this for personal use,  but maybe you will find it useful
https://hub.docker.com/r/bender77/unifi-api-browser/

**Comment by malle-pietje** [comment]
Nice! Thanks for the contribution!

**Comment by malle-pietje** [comment]
Had a closer look at the Dockerfile and I like the use of environment vars to "store" the credentials. I'll post this in the thread on the UBNT community.

**Comment by benderstwin** [comment]
My pleasure, thanks for the tool!
