### ISSUE TITLE
cannot connect database influx

### ISSUE THREAD

**Issue by cahpunke** [Art-of-WiFi/UniFi-API-browser#59]
helm my troubles

refer to the https://community.ubnt.com/t5/UniFi-Wireless/How-to-Display-connected-Clients-in-Grafana/m-p/2139761/highlight/false#M262208 page

curl -m 30 http://192.168.0.1/UniFi-API-browser-master/?action=list_clients > clientslist data=$(cat clientslist | grep objects_count | grep -Eo [0-9]+)
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
100 78820 0 78820 0 0 116k 0 --:--:-- --:--:-- --:--:-- 116k
curl: (6) Could not resolve host: data=40

 curl -i -X POST "http://192.168.0.1:8086/write?db=wificlients&precision=m" --data-binary 'clients;wifi=all value='$data''

HTTP/1.1 400 Bad Request
Content-Type: application/json
Request-Id: ca973028-2c3b-11e9-9367-54bef7386780
X-Influxdb-Build: OSS
X-Influxdb-Error: unable to parse 'clients;wifi=all value=': missing field value
X-Influxdb-Version: 1.7.3
X-Request-Id: ca973028-2c3b-11e9-9367-54bef7386780
Date: Sat, 09 Feb 2019 07:24:52 GMT
Content-Length: 75

{"error":"unable to parse 'clients;wifi=all value=': missing field value"}

**Comment by malle-pietje** [comment]
Hi, please do not pull data from the UniFi controller by using the API browser tool. That is not its intended use and functionality you might be relying on can break.

Instead, create your own minimal proxy script in PHP using the PHP API client which pulls the collection you need. See the examples here to get started:
https://github.com/Art-of-WiFi/UniFi-API-client/tree/master/examples

Especially this example will be a good start for your use case:
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/examples/list_alarms.php
