### ISSUE TITLE
api.err.IdInvalid when trying to change wlan password

### ISSUE THREAD

**Issue by aquilinux** [Art-of-WiFi/UniFi-API-browser#61]
Hi, i'm using change_wlan_password.php with debug on and this is the output:

-----------LOGIN-------------
[snip]
----------RESPONSE-----------
HTTP/1.1 200 
vary: Origin
Access-Control-Allow-Credentials: true
Access-Control-Expose-Headers: Access-Control-Allow-Origin,Access-Control-Allow-Credentials
Set-Cookie: unifises=63cXxTrlKXLA8BdpPwIvyhzAmcEYNmVu; Path=/; Secure; HttpOnly
Set-Cookie: csrf_token=XOt2sh4Vx3wfapaMVYKcp417hybbgzj9; Path=/; Secure
X-Frame-Options: DENY
Content-Type: application/json;charset=UTF-8
Content-Length: 41
Date: Mon, 11 Feb 2019 11:15:50 GMT

{ "data" : [ ] , "meta" : { "rc" : "ok"}}
-----------------------------

so login works, then:
---------cURL INFO-----------
Array
(
    [url] => https://10.255.255.186:8443/api/s/default/rest/wlanconf/guest
    [content_type] => application/json;charset=UTF-8
    [http_code] => 400
    [header_size] => 373
    [request_size] => 285
    [filetime] => -1
    [ssl_verify_result] => 18
    [redirect_count] => 0
    [total_time] => 0.559868
    [namelookup_time] => 1.7E-5
    [connect_time] => 0.000545
    [pretransfer_time] => 0.536978
    [size_upload] => 42
    [size_download] => 74
    [speed_download] => 132
    [speed_upload] => 75
    [download_content_length] => 74
    [upload_content_length] => 42
    [starttransfer_time] => 0.559847
    [redirect_time] => 0
    [redirect_url] => 
    [primary_ip] => 10.255.255.186
    [certinfo] => Array
        (
        )

    [primary_port] => 8443
    [local_ip] => 10.255.255.125
    [local_port] => 54288
    [request_header] => PUT /api/s/default/rest/wlanconf/guest HTTP/1.1
Host: 10.255.255.186:8443
Accept: */*
Cookie: unifises=63cXxTrlKXLA8BdpPwIvyhzAmcEYNmVu;csrf_token=XOt2sh4Vx3wfapaMVYKcp417hybbgzj9
Content-Type: application/json
Content-Length: 42

)
-------URL & PAYLOAD---------
https://10.255.255.186:8443/api/s/default/rest/wlanconf/guest
json={"x_passphrase":"mynewpassword"}
----------RESPONSE-----------
{ "data" : [ ] , "meta" : { "msg" : "api.err.IdInvalid" , "rc" : "error"}}
-----------------------------

What is wrong?

Thanks

**Comment by malle-pietje** [comment]
It seems as if you are not passing the id of the WLAN which you wish to update, or maybe you are not passing the correct site id (https://github.com/Art-of-WiFi/UniFi-API-client#important-notes)?

If that is correct in your opinion, please share the exact PHP code you are using including the variables used.

**Comment by aquilinux** [comment]
Hi, this is the Controller's URL: https://10.255.255.186:8443/manage/site/default/dashboard

So i'm assuming $site_id is "default". 

This is the code from config.php:

```
$controlleruser     = 'mycorrectuser';
$controllerpassword = "mycorrectpassword";
$controllerurl      = 'https://10.255.255.186:8443';
$controllerversion  = '5.9.29';
```

and this from change_wlan_password.php:

```
$site_id = 'default';
$wlan_id = 'guest';
$new_password = 'uninjured+workshop';

$unifi_connection = new UniFi_API\Client($controlleruser, $controllerpassword, $controllerurl, $site_id, $controllerversion);
$set_debug_mode   = $unifi_connection->set_debug($debug);
$loginresults     = $unifi_connection->login();
$results          = $unifi_connection->set_wlansettings($wlan_id, $new_password);

```

**Comment by malle-pietje** [comment]
This isn't that well documented for this specific method but the required `wlan_id` parameter needs to be the `_id` value for the WLAN you wish to change:
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/examples/change_wlan_password.php#L28

You can find this value by executing the `list_wlanconf()` and searching for the WLAN by `name` (SSID).

**Comment by aquilinux** [comment]
Thanks, it worked using the id.

Regards,

**Comment by malle-pietje** [comment]
You're welcome!
