### ISSUE TITLE
ENHANCEMENT

### ISSUE THREAD

**Issue by JSylvia007** [Art-of-WiFi/UniFi-API-browser#62]
After selecting the data you would like to see (and what gets shown in the window), have an option to export a "curl" (preferred) or "wget" command line to get the exact same output in the command line.

This would help me greatly in what I'm trying to accomplish with device presence and home automation.

**Comment by malle-pietje** [comment]
I will consider this, but really want to prevent support questions from users asking how to authenticate etc. This tool is intended to be a companion of the PHP API client which is why the used function is now also displayed above the data collection.

**Comment by JSylvia007** [comment]
I'd appreciate it. I think it would be simple enough to just put a line that says in order to use it, you need to set some variables for username, etc.

**Comment by malle-pietje** [comment]
I agree that adding a note will be a requirement, but the code will also need to fetch the actual URL from the API client (or some other approach) which adds extra maintenance effort that I would rather spend on adding other features. So if I do add this to the roadmap, it will not be high up on the list I'm afraid.
