### ISSUE TITLE
Getting the list of some API fields

### ISSUE THREAD

**Issue by host138** [Art-of-WiFi/UniFi-API-browser#65]
Hello. 

By API I get the clients' list (method list_clients) and for some clients there are fields: dev_cat, dev_family, os_name, dev_vendor - in form of integers. But they are transformed in admin area.
How can I get the full list of devices categories, OS names, devices types and their vendors to make their comparison and conversion. Thank you in advance.

![image_2019_04_08T11_37_05_334Z](https://user-images.githubusercontent.com/35528661/55722858-18967180-5a10-11e9-8615-13308d502de3.png)
![2019-04-08_150726](https://user-images.githubusercontent.com/35528661/55722857-18967180-5a10-11e9-9faa-abf81ca0fd32.png)

**Comment by malle-pietje** [comment]
These "translated" labels aren't available through the API I'm afraid. Maybe they are provided through one of the JS or JSON resources that are loaded?
