### ISSUE TITLE
REST API 

### ISSUE THREAD

**Issue by adolfozignago** [Art-of-WiFi/UniFi-API-browser#69]
It's possible to get the information of the unknown clients devices? 

The following information is for online user:

    {
        "site_id": "------------------------------------",
        "assoc_time": 1567060060,
        "latest_assoc_time": 1567060060,
        "oui": "Apple",
        "user_id": "------------------------------",
        "_id": "---------------------------",
        "mac": "xx:xx:xx:xx:xx:xx",
        "is_guest": false,
        "first_seen": 1566970983,
        "last_seen": 1567060190,
        "is_wired": false,
        "hostname": "Air-de-Adolfo",
        "_uptime_by_uap": 130,
        "_last_seen_by_uap": 1567060190,
        "_is_guest_by_uap": false,
        "ap_mac": "18:e8:29:e9:43:97",
        "channel": 36,
        "radio": "na",
        "radio_name": "wifi1",
        "essid": "unifi_client",
        "bssid": "18:e8:29:eb:43:97",
        "powersave_enabled": false,
        "is_11r": false,
        "ccq": 333,
        "rssi": 49,
        "noise": -107,
        "signal": -47,
        "tx_rate": 400000,
        "rx_rate": 400000,
        "tx_power": 34,
        "idletime": 0,
        "ip": "192.168.12.10",
        "dhcpend_time": 2600,
        "satisfaction": 0,
        "anomalies": 2048,
        "vlan": 0,
        "radio_proto": "ac",
        "uptime": 130,
        "tx_bytes": 1893139,
        "rx_bytes": 402627,
        "tx_packets": 2223,
        "tx_retries": 130,
        "wifi_tx_attempts": 1463,
        "rx_packets": 2333,
        "bytes-r": 5786,
        "tx_bytes-r": 4328,
        "rx_bytes-r": 1458,
        "authorized": true,
        "qos_policy_applied": true
    }
]
I need to get the same information for NO CONNECTED devices too. My platform needs that information to generate presence analytics and other kind of dashboards.

Thanks in advance!

**Comment by malle-pietje** [comment]
@adolfozignago Not possible with the UniFi platform; the UniFi APs do not collect probe requests with the exception of the AC-SHD. Unfortunately, even when using the AC-SHD, probe requests aren't made available through the API.

**Comment by adolfozignago** [comment]
Thats mean that I need to use AC-SHD and see how to get that information.

**Comment by malle-pietje** [comment]
We have several AC-SHDs for test purposes but haven’t figured it out. Will be interested to see what you can come up with. We chose to deploy custom collectors using rPi’s for such a project.

**Comment by adolfozignago** [comment]
thank you for the information,
I saw the airTime option on UAP-AC-SHD, the information is shown in graphic mode. I'm interested in the detail, can I'll get?

**Comment by malle-pietje** [comment]
That data isn’t available outside of the UniFi controller web UI, at least AFAIK.
