### ISSUE TITLE
Enhancement: Default to default site called default?

### ISSUE THREAD

**Issue by scyto** [Art-of-WiFi/UniFi-API-browser#72]
I was a little confused the first time when i loaded it up and nothing worked (my bad for not reading what was in front of me!)

Think about change so that the app automatically defaults to the site default if it is the only one present (heck if there is only one site automatically select it by default, irrespective of the name?).

**Comment by malle-pietje** [comment]
Ok, makes sense. Will consider adding that in a future release.
Thanks!
