### ISSUE TITLE
List IPS/IDS results in a  null output.

### ISSUE THREAD

**Issue by scyto** [Art-of-WiFi/UniFi-API-browser#73]
List IPS/IDS results in a null output.
Not sure what it is supposed to be fetching (hmm i will go look at the client php class and see).

There are IPS/IDS events in the alarms.... were these what were supposed to appear in the IPS/IDS list item?

**Comment by scyto** [comment]
oops is this my mistake because it defaults to last 24 hours?  not sure...

**Comment by malle-pietje** [comment]
Correct:
https://github.com/Art-of-WiFi/UniFi-API-client/blob/master/src/Client.php#L832
