### ISSUE TITLE
Consider changing alarms to alerts in UI?

### ISSUE THREAD

**Issue by scyto** [Art-of-WiFi/UniFi-API-browser#74]
Should it say alerts instead of alarms.

Alerts is the name of the data in the UI.
Alarms is the name of the data by API.

First is more obvious to those who only know the UI and are learning....

I am not sure what the answer is, was just a little confusing.

**Comment by malle-pietje** [comment]
I agree the names are a bit confusing but for consistency sake we chose the name used in the API URL which is '/list/alarm'. Since the API Browser was primarily built as a tool for developers I believe this makes sense.

**Comment by scyto** [comment]
Okedoke, I see the logic in the choice.
