### ISSUE TITLE
Not loading any sites

### ISSUE THREAD

**Issue by LadyDeathKZN** [Art-of-WiFi/UniFi-API-browser#79]
Hi, I have followed the instructions and changed the needed info in the config. But it says no sites listed when there is one site. I have tried the wifiMap, same issue nothing is listing. Is there a setting in the Unifi Controller that needs to be changed to allow API connection. 

https://community.ui.com/questions/UniFi-API-browser-tool-updates-and-discussion/30927150-dd44-40f7-96c0-9fbbfc673fb3#answer/60c7ad63-15e1-4c43-8673-bf54e50f6f24

I have this issue as the above link. Tried numerous cURL versions, ssl certificates, php versions. Please advise.

**Comment by malle-pietje** [comment]
This is most likely due to an error with the credentials. Please enable debug mode in the config file and check your web server error log and the browser console (in the developers tools section when using Chrome). There will some hints there as to what the issue is.
Please also share the controller version in your next post here.

**Comment by ehaughee** [comment]
I had a similar issue and once I checked my apache error logs I found I needed to install the curl extension for php:

    > sudo apt-get install php-curl
    > sudo service apache2 restart

Source: https://stackoverflow.com/questions/45001345/call-to-undefined-function-curl-version

**Comment by scyto** [comment]
this might be platform specific, i had someone report this same issue on my container - seems it only applies to the pi version of my container and not the x86 - will report back as i investigate.

**Comment by scyto** [comment]
this can also be caused by the year on the container being 1900 or 2071 (former with date command, latter in logs).
In my case was caused by https://stackoverflow.com/questions/66091978/corrupt-date-with-redis6-alpine-on-raspi
