### ISSUE TITLE
 Confirm works with 6.0.23?

### ISSUE THREAD

**Issue by joeknex** [Art-of-WiFi/UniFi-API-browser#82]
Hello, Can anyone confirm this works with V6.0.23? It worked before on V5 but not after upgrading. I'm getting the following error:

"We encountered the following error: we are unable to connect to the UniFi controller, A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (10060)!"

**Comment by malle-pietje** [comment]
We have it working with 6.0.26 just fine:
![6 0 26](https://user-images.githubusercontent.com/12016131/95331019-a96e3780-08a9-11eb-88a0-75167aa38cb6.jpg)

Perhaps you have MFA enabled? Can you share a screenshot of the error in its full context?

**Comment by joeknex** [comment]
Fixed now. The problem was related to the users.php file. I removed it then started working.
