### ISSUE TITLE
Connection Error

### ISSUE THREAD

**Issue by nickkecooper** [Art-of-WiFi/UniFi-API-browser#87]
I just purchased the Device Search tool and it seems like it can't connect to my controller. My controller faces the internet so I know its not that kind of issue. I put the correct url in the config.php file but I still don't have a connection.

**Comment by malle-pietje** [comment]
Hi, thanks for your purchase. Can you please send an email to **support AT artofwifi DOT net** with some more details such as the URL you are using?

**Comment by nickkecooper** [comment]
Thanks I emailed.
