### ISSUE TITLE
How can I see all energy (watts) being usage on the network 

### ISSUE THREAD

**Issue by nodecentral** [Art-of-WiFi/UniFi-API-browser#88]
Hi

I’m keen to save energy wherever I can and I can see that the Unifi controller shows the amount of power (watts) being used by each switch port, (poe_power).

is there a way to see all the energy (in watts) being across the entire UniFi network ?

**Comment by malle-pietje** [comment]
Understandable objective. The UniFi controller API only exposes the consumption of power through PoE, it doesn't show what the switch PSU is drawing and what its efficiency is. You might get more insights when using the new (upcoming) Powerstrip products in the UniFi family.
