### ISSUE TITLE
UDM Pro firmware beta version 1.11.0-14 and 1.11.0-15

### ISSUE THREAD

**Issue by kadamik** [Art-of-WiFi/UniFi-API-browser#92]
Both of these versions seem to break the login for the API login request.  I know it is just beta but I am afraid it will be a release candidate soon and I wanted to get ahead of the situation.  To me it looks like a login problem for the api, but I would be willing to test anything to see if it can be fixed or if I need to change any settings.

**Comment by malle-pietje** [comment]
Hi, we've had several similar reports but are unable to replicate the issues with the UDM PRO in our test lab running **1.11.0-14** and using the latest version of the API Client.

See my comment here:
https://community.ui.com/questions/PHP-client-class-to-access-the-UniFi-controller-API-updates-and-discussion/86cff6e2-06ad-46a2-8e0d-d91004f78752#answer/efea880b-54d1-4751-8468-3a19ce407380

If you could test the script I posted there and share the sanitized output that would be helpful.

**Comment by kadamik** [comment]
I just submitted script output.  

 

It freezes and will not complete.  I have to ctrl C to escape.

 

 

*   Trying 192.168.1.1:443...

* Connected to 192.168.1.1 (192.168.1.1) port 443 (#0)

* ALPN, offering h2

* ALPN, offering http/1.1

* successfully set certificate verify locations:

*  CAfile: /etc/ssl/certs/ca-certificates.crt

*  CApath: none

* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384

* ALPN, server accepted to use h2

* Server certificate:

*  subject: CN=unifi.local

*  start date: Mar 12 19:12:10 2021 GMT

*  expire date: Jun 15 19:12:10 2023 GMT

*  issuer: CN=unifi.local

*  SSL certificate verify result: self signed certificate (18), continuing
anyway.

* Using HTTP2, server supports multi-use

* Connection state changed (HTTP/2 confirmed)

* Copying HTTP/2 data in stream buffer to connection buffer after upgrade:
len=0

* Using Stream ID: 1 (easy handle 0x21ca370)

> HEAD / HTTP/2

Host: 192.168.1.1

accept: */*

accept-encoding: deflate, gzip

 

* old SSL session ID is stale, removing

* Connection state changed (MAX_CONCURRENT_STREAMS == 4294967295)!
