### ISSUE TITLE
Access to WLAN password

### ISSUE THREAD

**Issue by KetchupBomb** [Art-of-WiFi/UniFi-API-browser#94]
When you load the **Unifi Controller** > **Network** web UI, you can navigate to **WiFi**, load an individual network, and peek at the password in plain text:

![image](https://user-images.githubusercontent.com/13783465/140463166-88f5e1c9-0f7f-4a86-9633-0f8c0c08038b.png)

---

Within the Unifi API Browser, the closest Collection I can find is **list wlan configuration**, but there is no reference to the WLAN password in the output.

Is there another Collection I should be viewing? Is this field something the Unifi API Browser can gain access to?

**Comment by malle-pietje** [comment]
The key to look for is **x_passphrase**.

**Comment by KetchupBomb** [comment]
@malle-pietje , there is no `x_passphrase` key in the **list wlan configuration** Collection. Is it in another collection?

Is this field only accessible through the [Unifi API Client](https://github.com/Art-of-WiFi/UniFi-API-client)?

**Comment by malle-pietje** [comment]
@KetchupBomb it should actually be there if the SSID is protected with a WPA2 password/passphrase.

**Comment by malle-pietje** [comment]
If this is password to be entered through the captive portal you can find it in the **guest_access** section of the **list site settings** output. 

I personally find the new interface very confusing when it comes to setting up guest networks and always switch to the classic interface to get access to all controls.

**Comment by KetchupBomb** [comment]
@malle-pietje, this is a WPA2 network that I made on the UDM-Pro web UI. It is not associated with any captive or guest portals. And the "x_passphrase" is definitely not present -- both the API Browser web UI, and the API Client do not list this key for any of my WiFi networks. 

Is there a PHP recipe I can run to convince you? Is there additional information I can provide to debug why it's not showing when it seems like it should be?

**Comment by malle-pietje** [comment]
No need to convince me😉 Can you share a screenshot of the list of wireless networks using the classic interface?

**Comment by malle-pietje** [comment]
Also, which version of the Network Application are you running and which UDM firmware version?

**Comment by KetchupBomb** [comment]
UDM-Pro Unifi OS Version: `1.10.4`
Unifi Network Version: `6.4.54`

The WiFi in question is "Aperture Science" (though they're all configured the same, save the network/VLAN with which they're associated). Images attached.
![Screen Shot 2021-11-06 at 4 30 20 PM](https://user-images.githubusercontent.com/13783465/140626891-52d66cd4-ca96-4ae1-b77d-3b7733145851.png)
![Screen Shot 2021-11-06 at 4 30 37 PM](https://user-images.githubusercontent.com/13783465/140626893-18adb1e5-c1c7-47a4-97db-69e0a52a1247.png)
![Screen Shot 2021-11-06 at 4 31 16 PM](https://user-images.githubusercontent.com/13783465/140626894-ca60cd28-c5ae-48b4-8af5-1e44c73098e2.png)

**Comment by malle-pietje** [comment]
OK, I fired up the UDM PRO in our test lab and can see the password for a newly created SSID:
```
    {
        "_id": "6187d73ff392af04e887cac5",
        "enabled": true,
        "wpa3_support": false,
        "wpa3_transition": false,
        "security": "wpapsk",
        "wep_idx": 1,
        "wpa_mode": "wpa2",
        "wpa_enc": "ccmp",
        "pmf_mode": "disabled",
        "pmf_cipher": "auto",
        "usergroup_id": "6107bdff7fe01f067b62b78e",
        "wlan_band": "both",
        "ap_group_ids": [
            "6107bdff7fe01f067b62b798"
        ],
        "dtim_mode": "default",
        "dtim_ng": 1,
        "dtim_na": 3,
        "minrate_ng_enabled": false,
        "minrate_ng_advertising_rates": false,
        "minrate_ng_data_rate_kbps": 1000,
        "minrate_na_enabled": false,
        "minrate_na_advertising_rates": false,
        "minrate_na_data_rate_kbps": 6000,
        "mac_filter_enabled": false,
        "mac_filter_policy": "allow",
        "mac_filter_list": [],
        "bc_filter_enabled": false,
        "bc_filter_list": [],
        "group_rekey": 3600,
        "hotspot2conf_enabled": false,
        "bss_transition": true,
        "auth_cache": true,
        "schedule_enabled": false,
        "name": "My test WPA SSID",
        "x_passphrase": "dezeisgeheim",
        "networkconf_id": "6107bdff7fe01f067b62b78d",
        "radius_das_enabled": false,
        "site_id": "6107bdf97fe01f067b62b77a",
        "iapp_enabled": true,
        "x_iapp_key": "40c5a28515861cc58685abfe39db3942",
        "optimize_iot_wifi_connectivity": false,
        "dtim_6e": 3,
        "wlan_bands": [
            "2g",
            "5g"
        ]
    }
```
The SSID was created through the Classic interface like so:
![Screenshot 2021-11-07 144338](https://user-images.githubusercontent.com/12016131/140647603-3a809280-1d3c-4fb7-8c77-c01aaa01ac83.png)

Versions are:

- UDM firmware: 1.11.0-16
- Network Application: 6.5.50

**Comment by malle-pietje** [comment]
The same applies to our software-based controller running version 6.4.54.

**Comment by malle-pietje** [comment]
The only remaining thing I can think of is the permissions of the admin account you're using to connect through the API.

**Comment by KetchupBomb** [comment]
> The only remaining thing I can think of is the permissions of the admin account you're using to connect through the API.

You're right. I set the account to be "View Only" initially. When I switch it to "Administrator" (or "Site Admin"), I am able to see the x_password field. I may have missed documentation that points this out (sorry!). It's strange that this nuance of read vs write permissions causes some fields to display or not. 🤷‍♂️ 

Thanks for your patience and help.

**Comment by malle-pietje** [comment]
Thanks for the feedback, good to hear. Will add a note to the README for the PHP API client to reflect your findings (not something I’d seen before myself).

**Comment by KetchupBomb** [comment]
@malle-pietje, btw, I bet this is exactly what was happening in https://github.com/Art-of-WiFi/UniFi-API-client/issues/129.

cc @NickDunas

**Comment by malle-pietje** [comment]
Yes, correct. I've added a note on this to the README files for both the API Client and the API Browser. Thanks for your help with this!
