### ISSUE TITLE
Unifi 7.0 Controller API Issue

### ISSUE THREAD

**Issue by sanxeon** [Art-of-WiFi/UniFi-API-browser#98]
Hi Guys,

When you above API document to authenticate customers we are getting  [api] api.err.Invalid: //api/login error on controller veriosn 7.1.66.

Do you have to change anything on the code ?

**Comment by malle-pietje** [comment]
The client works fine with that version. Please share your code and also confirm the URL you’re using (direct link to controller or unifi.ui.com). Even better is to share sanitized debug output.

**Comment by malle-pietje** [comment]
If your issue is related to the API client class please open an issue for that repo. We’ll then close this one.
